# Generated by Django 5.1.4 on 2024-12-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookrequest'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookloan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='bookloan',
            constraint=models.UniqueConstraint(condition=models.Q(('return_date__isnull', True)), fields=('user', 'book'), name='unique_active_loan'),
        ),
    ]
